activation: gelu
alias: null
batch_size: 128
conv_hidden_size: 64
dataloader_kwargs: null
decoder_input_size_multiplier: 0.5
decoder_layers: 5
distil: true
drop_last_loader: false
dropout: 0.2
early_stop_patience_steps: -1
encoder_layers: 5
exclude_insample_y: false
factor: 3
futr_exog_list:
- Open
- High
- Low
- Volume
- SMA_50
- SMA_200
- RSI
- MACD
- MACD_signal
- weighted_sentiment
- weighted_sentiment_change
- tweet_count
h: 7
hidden_size: 128
hist_exog_list: null
inference_windows_batch_size: 1024
input_size: 20
learning_rate: 0.001
loss: !!python/object:neuralforecast.losses.pytorch.MAE
  _backward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _backward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _buffers: {}
  _forward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks_always_called: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
  - []
  _is_full_backward_hook: null
  _load_state_dict_post_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _modules: {}
  _non_persistent_buffers_set: !!set {}
  _parameters: {}
  _state_dict_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  horizon_weight: null
  is_distribution_output: false
  output_names:
  - ''
  outputsize_multiplier: 1
  training: true
lr_scheduler: null
lr_scheduler_kwargs: null
max_steps: 250
n_head: 12
num_lr_decays: -1
optimizer: null
optimizer_kwargs: null
random_seed: 1
scaler_type: robust
start_padding_enabled: false
stat_exog_list: null
step_size: 1
val_check_steps: 25
valid_batch_size: null
valid_loss: null
windows_batch_size: 1024
